/**
 * Decorative Wall Paneling expressed as a reusable variable-scope template.
 * Specialized compute (derived panels, removal type, work-area services)
 * still lives in decorative-wall-paneling.ts. This definition is the
 * shared contract for rates vs. quantities and future custom-work reuse.
 */
import {
  DECORATIVE_WALL_PANELING_CALCULATOR_ID,
  DECORATIVE_WALL_PANELING_TITLE,
  DEFAULT_DECORATIVE_WALL_PANELING_RATES,
} from "@/lib/estimate-calculators/decorative-wall-paneling";
import type { VariableScopeTemplate } from "@/lib/estimate-calculators/variable-scope";

const rates = DEFAULT_DECORATIVE_WALL_PANELING_RATES;

export const DECORATIVE_WALL_PANELING_TEMPLATE: VariableScopeTemplate = {
  calculatorId: DECORATIVE_WALL_PANELING_CALCULATOR_ID,
  title: DECORATIVE_WALL_PANELING_TITLE,
  components: [
    {
      key: "wallWidthFt",
      name: "Wall width",
      inputType: "measurement",
      units: "ft",
      quantityKey: "wallWidthFt",
      persistRate: false,
      resetQuantity: true,
      customerVisible: false,
      section: "measurements",
    },
    {
      key: "wallHeightFt",
      name: "Wall height",
      inputType: "measurement",
      units: "ft",
      quantityKey: "wallHeightFt",
      persistRate: false,
      resetQuantity: true,
      customerVisible: false,
      section: "measurements",
    },
    {
      key: "panels",
      name: "Panel / sheet quantity",
      inputType: "count",
      units: "4x8 panel-equivalent",
      quantityKey: "panelQuantity",
      rateKey: "panelRate",
      defaultRate: rates.panelRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "measurements",
    },
    {
      key: "removal",
      name: "Existing-material removal",
      inputType: "measurement",
      units: "sq ft",
      quantityKey: "removalType",
      rateKey: "removalRatePerSqFt",
      defaultRate: rates.removalRatePerSqFt,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "measurements",
    },
    {
      key: "slidingPatioDoors",
      name: "Sliding / patio door openings",
      inputType: "count",
      units: "each",
      quantityKey: "slidingPatioDoors",
      rateKey: "slidingPatioDoorRate",
      defaultRate: rates.slidingPatioDoorRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "standardDoors",
      name: "Standard door openings",
      inputType: "count",
      units: "each",
      quantityKey: "standardDoors",
      rateKey: "standardDoorRate",
      defaultRate: rates.standardDoorRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "windows",
      name: "Window openings",
      inputType: "count",
      units: "each",
      quantityKey: "windows",
      rateKey: "windowRate",
      defaultRate: rates.windowRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "receptacles",
      name: "Receptacles / outlets",
      inputType: "count",
      units: "each",
      quantityKey: "receptacles",
      rateKey: "receptacleRate",
      defaultRate: rates.receptacleRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "switches",
      name: "Switches",
      inputType: "count",
      units: "each",
      quantityKey: "switches",
      rateKey: "switchRate",
      defaultRate: rates.switchRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "lightFixtures",
      name: "Light fixtures",
      inputType: "count",
      units: "each",
      quantityKey: "lightFixtures",
      rateKey: "lightFixtureRate",
      defaultRate: rates.lightFixtureRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "counts",
    },
    {
      key: "trim",
      name: "Finish trim / transitions",
      inputType: "allowance",
      units: "usd",
      quantityKey: "trimAllowance",
      rateKey: "defaultTrimAllowance",
      defaultRate: rates.defaultTrimAllowance,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "cleanup",
      name: "Construction cleanup / debris handling",
      inputType: "allowance",
      units: "usd",
      quantityKey: "cleanupAllowance",
      rateKey: "defaultCleanupAllowance",
      defaultRate: rates.defaultCleanupAllowance,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsHandling",
      name: "Work-area / contents handling",
      inputType: "rate",
      units: "usd",
      quantityKey: "contentsHandlingLevel",
      rateKey: "contentsHandlingLightRate",
      defaultRate: rates.contentsHandlingLightRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsProtection",
      name: "Contents protection",
      inputType: "rate",
      units: "usd",
      quantityKey: "contentsProtectionLevel",
      rateKey: "contentsProtectionLightRate",
      defaultRate: rates.contentsProtectionLightRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "belongingsCleanup",
      name: "Additional customer-belongings cleaning",
      inputType: "rate",
      units: "usd",
      quantityKey: "belongingsCleanupLevel",
      rateKey: "belongingsCleanupLightRate",
      defaultRate: rates.belongingsCleanupLightRate,
      persistRate: true,
      resetQuantity: true,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsHandlingModerateRate",
      name: "Contents handling — moderate",
      inputType: "rate",
      units: "usd",
      rateKey: "contentsHandlingModerateRate",
      defaultRate: rates.contentsHandlingModerateRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsHandlingHeavyRate",
      name: "Contents handling — heavy",
      inputType: "rate",
      units: "usd",
      rateKey: "contentsHandlingHeavyRate",
      defaultRate: rates.contentsHandlingHeavyRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsProtectionModerateRate",
      name: "Contents protection — moderate",
      inputType: "rate",
      units: "usd",
      rateKey: "contentsProtectionModerateRate",
      defaultRate: rates.contentsProtectionModerateRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "contentsProtectionHeavyRate",
      name: "Contents protection — heavy",
      inputType: "rate",
      units: "usd",
      rateKey: "contentsProtectionHeavyRate",
      defaultRate: rates.contentsProtectionHeavyRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "belongingsCleanupModerateRate",
      name: "Belongings cleanup — moderate",
      inputType: "rate",
      units: "usd",
      rateKey: "belongingsCleanupModerateRate",
      defaultRate: rates.belongingsCleanupModerateRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
    {
      key: "belongingsCleanupHeavyRate",
      name: "Belongings cleanup — heavy",
      inputType: "rate",
      units: "usd",
      rateKey: "belongingsCleanupHeavyRate",
      defaultRate: rates.belongingsCleanupHeavyRate,
      persistRate: true,
      resetQuantity: false,
      customerVisible: false,
      section: "allowances",
    },
  ],
};
