#!/usr/bin/env bash
# Cloud Agent environment "install" step for TBBT.
#
# Idempotent: prepares a local PostgreSQL server, project dependencies, the
# Prisma client, and the database schema so `npm run dev` works with no
# external services. Safe to re-run and safe to run at build time.
set -euo pipefail

cd "$(dirname "$0")/.."

PG_VERSION=16
PG_CLUSTER=main
DB_USER=tbbt
DB_PASSWORD=tbbt
DB_NAME=tbbt

echo "[setup] Ensuring PostgreSQL ${PG_VERSION} is installed..."
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq "postgresql-${PG_VERSION}" postgresql-contrib
fi

echo "[setup] Ensuring the PostgreSQL cluster is running..."
if ! pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
  sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start || true
fi

# Wait for the socket to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "[setup] Ensuring the '${DB_USER}' role and '${DB_NAME}' database exist..."
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}' SUPERUSER;"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
  || sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"

# Next.js auto-loads .env. Keep the developer's file if present; otherwise seed
# a local-only configuration (no secrets, fake payment/messaging adapters).
if [ ! -f .env ]; then
  echo "[setup] Writing local .env ..."
  cat > .env <<'ENVEOF'
# Local Cloud Agent development environment (generated by scripts/cloud-agent-setup.sh).
# Local PostgreSQL cluster created during environment setup.
DATABASE_URL="postgresql://tbbt:tbbt@127.0.0.1:5432/tbbt?schema=public"

NEXT_PUBLIC_APP_URL="http://localhost:43217"

# Local/demo adapters so payments and messaging never hit real providers.
TBBT_PAYMENTS_ADAPTER=fake
TBBT_PAYMENTS_FAKE_READY=1
TBBT_SAAS_BILLING_ADAPTER=fake
TBBT_CUSTOMER_MESSAGING_ADAPTER=fake
ENVEOF
fi

echo "[setup] Installing npm dependencies..."
npm ci

echo "[setup] Applying database migrations..."
# `prisma` reads DATABASE_URL from the environment; load it from .env.
set -a
# shellcheck disable=SC1091
. ./.env
set +a
npx prisma migrate deploy

echo "[setup] Done. Start the app with: npm run dev"
