/**
 * Provider-neutral AI types. Business calculations, authorization, and
 * permissions stay outside this module.
 */

export const AI_TASK_TYPES = [
  "COACH_ASK",
  "WRITING",
  "MARKETING_DRAFT",
  "REVIEW_RESPONSE",
  "KNOWLEDGE_ASK",
  "WEEKLY_PLAN",
  "CAMPAIGN_IDEAS",
] as const;
export type AiTaskType = (typeof AI_TASK_TYPES)[number];

export const AI_INTERACTION_STATUSES = [
  "PENDING",
  "COMPLETED",
  "FAILED",
  "SKIPPED_NOT_CONNECTED",
  "VALIDATION_FAILED",
] as const;
export type AiInteractionStatus = (typeof AI_INTERACTION_STATUSES)[number];

export const AI_CONVERSATION_AREAS = [
  "COACH",
  "KNOWLEDGE",
  "MARKETING",
  "REVIEW",
  "WRITING",
] as const;
export type AiConversationArea = (typeof AI_CONVERSATION_AREAS)[number];

export const WRITING_ACTIONS = [
  "IMPROVE",
  "FIX_GRAMMAR",
  "SHORTER",
  "FRIENDLIER",
  "PROFESSIONAL",
  "WRITE_FOR_ME",
  "KEEP_MINE",
] as const;
export type WritingAction = (typeof WRITING_ACTIONS)[number];

export const WRITING_ACTION_LABELS: Record<WritingAction, string> = {
  IMPROVE: "Improve",
  FIX_GRAMMAR: "Fix Grammar",
  SHORTER: "Shorter",
  FRIENDLIER: "Friendlier",
  PROFESSIONAL: "Professional",
  WRITE_FOR_ME: "Write It For Me",
  KEEP_MINE: "Keep Mine",
};

export function isWritingAction(value: string): value is WritingAction {
  return (WRITING_ACTIONS as readonly string[]).includes(value);
}

export const AI_NOT_CONNECTED_MESSAGE =
  "AI is not connected. TBBT is using recorded facts and templates only. Nothing here was generated by a model provider.";

export const AI_FAILURE_MESSAGE =
  "The AI provider could not complete that request. Recorded TBBT facts were not changed. You can retry once.";

export const AI_VALIDATION_MESSAGE =
  "The AI response could not be used because it failed structured validation. Recorded facts were not changed.";

export type AiUsage = {
  promptTokens?: number;
  completionTokens?: number;
};

export type AiProviderRequest = {
  taskType: AiTaskType;
  system: string;
  user: string;
  jsonSchemaName: string;
  maxOutputTokens: number;
};

export type AiProviderSuccess = {
  ok: true;
  provider: string;
  model: string;
  text: string;
  usage?: AiUsage;
  latencyMs: number;
};

export type AiProviderFailure = {
  ok: false;
  provider: string;
  model?: string;
  error: string;
  retryable: boolean;
  latencyMs: number;
};

export type AiProviderResult = AiProviderSuccess | AiProviderFailure;

export interface AiProvider {
  readonly id: string;
  readonly connected: boolean;
  complete(request: AiProviderRequest): Promise<AiProviderResult>;
}

export type CitedFact = {
  key: string;
  label: string;
  value: string;
  href?: string;
};

export type StructuredAiOutput = {
  text: string;
  stance: "FACT" | "RECOMMENDATION" | "MIXED";
  citedFactKeys: string[];
  notes?: string;
};

export type AiRunResult = {
  status: AiInteractionStatus;
  connected: boolean;
  provider: string | null;
  model: string | null;
  output: StructuredAiOutput | null;
  message: string;
  failureReason?: string;
  retryable: boolean;
  usage?: AiUsage;
  interactionId?: string;
};

export const AI_MAX_INPUT_CHARS = 8_000;
export const AI_MAX_OUTPUT_TOKENS = 800;
export const AI_MAX_RETRIES = 1;
